language: python

python:
    - 2.7
    - 3.5

cache:
    directories:
        - $HOME/.cache/pip

env:
    - NUMPY_VERSION=1.11.1 OMP_NUM_THREADS=2

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython numba
    - conda install --yes -c bccp pfft-python mpsort mpi4py
    - python setup.py install

script:
    - pip install runtests
    - python run-tests.py --mpirun="mpirun -np 4"
    - bash check_tag.sh pmesh/version.py

deploy:
    - provider: pypi
      distributions: sdist
      user: "rainwoodman"
      password:
          secure: "WKaAWiGPxKlEQRmI1tNSRfBBcwg1Jdrw3kcTTsCEM1r8IH5I2Iz2rFACA0ZifqzA5BwketMV91u7jsKds8QORD2qb+AcGam7/bqOpfjQ+rK+NUcWQzTYaTUehN/vpgl8+DV/JFyW+DPQ5oeCyOke5JLhviEK5707rB82aIL2BD0BQWYxSOYimqQK8GeQePbU4Vxg5ZYay5pVnuroVbn9lAHymDTLvrGkJBtGK6w1zmGq4K7wGRc8PKaLIX91WExrdF1zqdiADNxzEsLoB+4cHIo/iCRfE/mYSo2AX36m+Odgx10TurZwYgAxY/6ybVs6y1Co9K2DIBTxALIFhDgfMWVSirotFZRDJiSgvbYNWYw61c0mFM7smAD90zijy/M4orQXR4TzU3+77guwQXV6SV+OEh1zkahQD8o6KnLBAp0oiSPFjk3r8VBg3mAA/dIb3fbml6j4G61BLpyhzeS22FOwuM18nw6LfdKdm3D4UBs/JIcRFLr5V+24NuD7DEF31FBB6+Diu2jFB8ANSwhw8C1FT3zDHMr2xfXrmhVGxfTTboNzzgqn7LJBkE5QXw9Mn2U0471T2Q3jDFenuzb0KJVkCFQ1etiiSmlt6P0g0inBzvKwAgiBUkNguimZb3uRpBDV9UFxPd94dz+Ws5nKpxKTT0oDiwQBtR3BDAMEwiw="
      on:
        tags   : true
        condition : ${TRAVIS_JOB_NUMBER##*.} == 1
